permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Huang Moyue
  email: huangmoyue at 163.com
  github: https://github.com/eledata
  linkedin: https://cn.linkedin.com/in/huangmoyue
# 站点信息
title: 黄默悦的博客
description: My personal blog
url: http://eledata.github.io

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# disqus 设置
disqus:
  shortname: ele_cloud

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档